name: Deploy to Dev EKS

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.29.0

    - name: Setup Kubeconfig
      run: |
        aws eks update-kubeconfig --name my-eks-cluster --region eu-central-1

    - name: Deploy App
      run: |
        kubectl apply -f manifests/
