name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-test-scan-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker image
        run: |
          IMAGE_TAG=latest
          docker build -t frontend ./src/frontend
          docker tag frontend:latest ${{ steps.login-ecr.outputs.registry }}/frontend:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/frontend:$IMAGE_TAG

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region us-west-2 --name online-boutique-cluster

      - name: Deploy to EKS
        run: |
          kubectl apply -f release/kubernetes-manifests.yaml
