name: PR Checks - Static and Security Analysis

on:
  pull_request:
    branches: [ dev ]

jobs:
  static-analysis:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: sonarsource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  image-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Image
      run: docker build -t myservice:test ./src/
    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: myservice:test
        format: table
        exit-code: 1
